<?php

namespace Athena\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository {

    public function getConversationByUsers(Athena\ChatBundle\Entity\Utilisateur $utilisateur1, Athena\ChatBundle\Entity\Utilisateur $utilisateur2) {

        $qb = $this->_em->createQueryBuilder();
        $qb2 = $this->_em->createQueryBuilder();
        $qb->select('c')
                ->from('Conversation', 'c')
                ->join('c.utilisateurs', 'us')
                ->join('us.utilisateur', 'u')
                ->where(
                        $qb->expr()->in('u.login', array(':user1Login', ':user2Login'))
                )
                ->andWhere(
                        $qb->expr()->notIn('c.id', 
                                $qb2->select('c2')
                                ->join('c.utilisateurs', 'us2')
                                ->join('us.utilisateur', 'u2')
                                ->where('u2.login <> :user1Login')
                                ->andWhere('u2.login <> :user2Login')
                        )
                        ->getDQL()
                )
                ->setParameter(':user1Login', $utilisateur1->getLogin())
                ->setParameter(':user2Login', $utilisateur2->getLogin());

        return $qb  ->getQuery()
                    ->getResult();
    }

}
