<?php

namespace Athena\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurConversationRepository extends EntityRepository
{
}
